# Site settings
baseurl: ''
url: 'https://www.rada.if.ua'

encoding: UTF-8
lang: uk_UA
timezone: Europe/Kiev

title: Ради в Івано-Франківській області
description: Представни́цькі органи влади Івано-Франківської області
name: Місцеві ради
brand: Рада
logo: "/assets/images/logo.svg"

author:
  name: Vasyl&nbsp;Mosiychuk
  website: http://www.vasyl.net
  email: info@vasyl.net
developer:
  name: vasyl.net
  website: http://www.vasyl.net
  email: info@vasyl.net

contact:
  name: Вебсайт представни́цьких органів&nbsp;влади
  address: 76018, м. Івано-Франківськ, вул.&nbsp;Січових&nbsp;Стрільців,&nbsp;56
  phone_main: (067) 433 00 66
  phone_hot:  (067) 433 00 66
  phone_fax:  (067) 433 00 66
  email: info@rada.if.ua
  www: https://www.rada.if.ua/

legal:
  name: Вебсайт представни́цьких органів&nbsp;влади
  address: 76018, м. Івано-Франківськ, вул.&nbsp;С.&nbsp;Стрільців,&nbsp;56
  phone:
    main: (067) 433 00 66
    hot:  (067) 433 00 66
    fax:  (067) 433 00 66
  email: info@rada.if.ua
  www: https://www.rada.if.ua/

defaults:
  - scope:
      path: /*/data/*.json
    values:
      sitemap: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: /*/decisions/
      type: "decisions"
    values:
      layout: "decisions"
  - scope:
      path: /*/news/
      type: "news"
    values:
      layout: "news"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-timeago
  - jekyll-paginate-v2

compress_html:
  clippings: all
  comments: [""]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
