# Site settings
baseurl: ''
url: 'https://www.rada.if.ua'

encoding: UTF-8
lang: uk_UA

brand: Рада
name: Місцеві Ради
title: Територіальні громади Івано-Франківської області
description: >
  Представницькі органи територіального самоврядування місцевих громад Івано-Франківській області, Україна.
keywords: рада, обласна, міська, районна, селищна, сільська
jumbotron:
  title: Jumbotron Title
  description: Jumbotron Description
album:
  title: Album Title
  description: Album Description

collections:
  news:
    output: true
  decisions:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
  -
    scope:
      path: /*/decisions/
      type: "decisions"
    values:
      layout: "decisions"
  -
    scope:
      path: /*/news/
      type: "news"
    values:
      layout: "news"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "councils"

pagination:
  enabled: true
  per_page: 12

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-redirect-from
  # The following plugins are always used by GH-Pages
  - jekyll-paginate-v2

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .git
  - .github
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - config
  - Gruntfile.js
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - tmp

compress_html:
  clippings: all
  comments: [""]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
